syntax = "proto2";

package mbo.proto.tests;

message TestMessage {
  optional string name = 1;
  optional int32 num = 2;
  optional double val = 3;
}

message TestMessage2 {
  repeated int32 num = 1;
  optional TestMessage one = 2;
  repeated TestMessage more = 3;
}

message RequiredMessage {
  required int32 value = 1;
}

message ExtensibleMessage {
  extensions 100 to max;
}

extend ExtensibleMessage {
  optional int32 extension_value = 100;
}

message ExtensionContainer {
  optional ExtensibleMessage child = 1;
}
