# SPDX-FileCopyrightText: Copyright (c) M. Boerger, the MBO Works authors
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:private"])

licenses(["notice"])

cc_library(
    name = "file_cc",
    srcs = ["file.cc"],
    hdrs = [
        "file.h",
        "file_impl.h",
    ],
    implementation_deps = [
        ":silent_error_collector_cc",
        "@com_google_absl//absl/log:absl_log",
        "@com_google_protobuf//src/google/protobuf/io",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings:str_format",
        "@com_google_protobuf//:protobuf",
        "@com_google_protobuf//:protobuf_headers",
    ],
)

cc_test(
    name = "file_test",
    srcs = ["file_test.cc"],
    deps = [
        ":file_cc",
        ":matchers_cc",
        ":status_matchers_cc",
        "//mbo/proto/tests:simple_message_cc_proto",
        "@com_google_googletest//:gtest",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "matchers_cc",
    testonly = 1,
    srcs = ["matchers.cc"],
    hdrs = ["matchers.h"],
    implementation_deps = [
        "@com_google_absl//absl/log:absl_log",
        "@com_google_absl//absl/strings",
        "@com_google_protobuf//src/google/protobuf/io:tokenizer",
        "@com_googlesource_code_re2//:re2",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_absl//absl/log:absl_check",
        "@com_google_googletest//:gtest",
        "@com_google_protobuf//:differencer",
        "@com_google_protobuf//:protobuf",
        "@com_google_protobuf//:protobuf_headers",
    ],
)

cc_test(
    name = "matchers_test",
    srcs = ["matchers_test.cc"],
    deps = [
        ":matchers_cc",
        "//mbo/proto:parse_text_proto_cc",
        "//mbo/proto/tests:test_cc_proto",
        "@com_google_googletest//:gtest",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "parse_text_proto_cc",
    srcs = ["parse_text_proto.cc"],
    hdrs = ["parse_text_proto.h"],
    implementation_deps = [
        ":silent_error_collector_cc",
        "@com_google_absl//absl/log:absl_log",
        "@com_google_absl//absl/strings:str_format",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_absl//absl/log:absl_check",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@com_google_protobuf//:protobuf",
        "@com_google_protobuf//:protobuf_headers",
    ],
)

cc_test(
    name = "parse_text_proto_test",
    srcs = ["parse_text_proto_test.cc"],
    deps = [
        ":matchers_cc",
        ":parse_text_proto_cc",
        "//mbo/proto/tests:simple_message_cc_proto",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@com_google_googletest//:gtest",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_library(
    name = "silent_error_collector_cc",
    srcs = ["silent_error_collector.cc"],
    hdrs = ["silent_error_collector.h"],
    implementation_deps = [
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/strings:str_format",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_absl//absl/base:log_severity",
        "@com_google_protobuf//src/google/protobuf/io:tokenizer",
    ],
)

cc_test(
    name = "silent_error_collector_test",
    srcs = ["silent_error_collector_test.cc"],
    deps = [
        ":silent_error_collector_cc",
        "@com_google_absl//absl/base:log_severity",
        "@com_google_absl//absl/strings",
        "@com_google_googletest//:gtest",
        "@com_google_googletest//:gtest_main",
        "@com_google_protobuf//src/google/protobuf/io:tokenizer",
    ],
)

cc_library(
    name = "status_matchers_cc",
    testonly = 1,
    hdrs = ["status_matchers.h"],
    visibility = [
        # Do not use this elsewhere. Instead:
        #   - just upgrade your Abseil dependency.
        #     #include "absl/status/status_matchers"
        #   - use @mboworks_mbo//mbo/testing:status_cc
        #     #include "mbo/testing/status.h"
        "//visibility:private",
    ],
    deps = [
        "@com_google_absl//absl/status",
        "@com_google_googletest//:gtest",
    ],
)
